### ISSUE TITLE
Support handling of function declarations, object literals and catch clauses

### ISSUE THREAD

**Issue by marcokam** [spyfu/underscore-template-strict-loader#1]
Very nice library you have here!  I've been looking for something like this to enable the use of babel in our underscore templates.  Especially like the use of AST to find all the free variables in the templates.

We have some legacy code in our project where the templates are being used in ways that probably they wouldn't normally be.  Basically, we are writing a lot of javascript in our templates such as `defining functions`, calling functions with `object literals,` and doing `try catch`.

When I used this package to load our templates, it was adding `data.` in places where it shouldn't have been.

Here are some examples of template code where `data` is appended in the incorrect places:

**Function Declarations**
template: `<% function hello(world) {} %>`
result: `function data.hello(data.world) {}`

**Object Literals**
template: `<% function test(options) {}
test({hello: world});
%>`
result: `function data.test(data.options) {}
data.test({data.hello: data.world});`

**Catch Clauses**
template: `<% try { JSON.stringify("bad json"); } catch(e) { } %>`
result: `try { JSON.stringify("bad json"); } catch(data.e) { }`

I'm planning on submitting a PR to fix these particular issues that I've found.

**Comment by scottbedard** [comment]
Thanks for the PR, on first glance it looks good! I'll clone down your branch and try to get it merged  tomorrow.
