### ISSUE TITLE
getting error:  data.__ is not a function

### ISSUE THREAD

**Issue by dhaval-lila** [spyfu/underscore-template-strict-loader#4]
I am using underscore-template-strict-loader something like this : 
```
const loader = require('underscore-template-strict-loader');
module.exports = {
  process(src,filename) {
    console.log(`${loader(src)}`);
    return `${loader(src)}`;
  },
};
```
this is jest transformer for ejs file to convert to js under strict mode but `<%= __('Create Dashboard' ) %>` get converted to  `((data.__t=( data.__('Create Dashboard' ) ))==null?'':data.__t)` and jest throws error `TypeError: data.__ is not a function` , I looked into your code , I think there might be problem with `isUnderscoreVariable(node)` though I am not sure.

**Comment by scottbedard** [comment]
Closing, this repository is deprecated and no longer maintained.
